server:
  port: 8082

spring:
  application:
    name: tl-live-user-provider
  cloud:
    nacos:
      discovery:
        server-addr: nacos.tllive.com:8848
        namespace: tl-live
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.223.132:3306/tllive?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  data:
    redis:
      host: 192.168.233.132
      port: 6379
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://nacos.tllive.com:8848?namespace=tl-live
    id: nacos-registry
  protocol:
    name: dubbo
    port: -1

tllive:
  sms:
    ccp:
      # 测试环境，实际发短信。
      test: true
      smsServerIp: app.cloopen.com
      port: 8883
      accountSId: 2c94811c92f9eb9801934a33728215c0
      accountToken: 8657bcb141d94d1085f06b86cb9fb43e
      appId: 2c94811c92f9eb9801934a33743015c7
      templateId: 1
      testPhone: 19047109270