server:
  port: 8084

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.233.132:3306/tllive_cosid?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#    qos-enable: false
#  registry:
#    address: nacos://127.0.0.1:8848?namespace=tl-live
#    id: nacos-registry
#    protocol:
#  protocol:
#    name: dubbo
#    port: -1
#
#cosid:
#  enabled: true
#  namespace: tl-live
#  machine:
#    enabled: true
#    distributor:
#      type: jdbc
#  # 非严格递增的雪花ID
#  snowflake:
#    enabled: true
#    provider:
#      snowflakeId:
#        clock-sync: true
#        sequence-reset-threshold: 10
#    #关闭默认的__share__序列分发器 如果不关闭，会有Bean冲突问题
#    share:
#      enabled: false
#  # 严格递增的SegmentID
#  segment:
#    enabled: true
#    mode: chain
#    distributor:
#      type: jdbc
#      jdbc:
#        # 初始化cosid表
#        enable-auto-init-cosid-table: true
#    chain:
#      safe-distance: 10
#    provider:
#      sequence:
#        offset: 100
#        step: 1
#    #关闭默认的__share__序列分发器
#    share:
#      enabled: false
