server:
  port: 8085
#spring:
#  application:
#    name: tl-live-im
#
#tllive:
#  im:
#    thread:
#      pool:
#        corePoolSize: 2
#        maxPoolSize: 10
#        queueCapacity: 10000
#        keepAliveTime: 600
#    heartbeat:
#      timeout:
#        seconds: 30
#rocketmq:
#  name-server: 192.168.233.132:9876
#  producer:
#    group: tl-live-im-producer